[package]
name = "lsb_hide"
version = "0.1.0"
edition = "2024"
description = "LSB hide and recover program for BMP image."

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
colored = "3.0.0"
