name: Rust CI & Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # 监听版本 tag
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install latest stable Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build (Release mode)
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose

  release_build:
    name: Build & Release for ${{ matrix.target }}
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [test_and_build]

    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
        
        include:
          - target: x86_64-unknown-linux-gnu
            bin_suffix: ""
            asset_name: linux-x64
          - target: x86_64-pc-windows-msvc
            bin_suffix: ".exe"
            asset_name: windows-x64
          - target: x86_64-apple-darwin
            bin_suffix: ""
            asset_name: macos-x64

    steps:
      - uses: actions/checkout@v5

      - name: Cross Build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          args: --release --locked

      - name: Set Binary Path and Name
        id: vars
        shell: bash
        run: |
          BIN_NAME="lsb_hide"
          echo "bin_path=target/${{ matrix.target }}/release/${BIN_NAME}${{ matrix.bin_suffix }}" >> $GITHUB_OUTPUT
          echo "asset_name=${BIN_NAME}-${{ github.ref_name }}-${{ matrix.asset_name }}" >> $GITHUB_OUTPUT
      
      - name: Compress Binary
        run: |
          mkdir staging
          cp ${{ steps.vars.outputs.bin_path }} staging/
          
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            zip -j ${{ steps.vars.outputs.asset_name }}.zip staging/*
            echo "archive_path=${{ steps.vars.outputs.asset_name }}.zip" >> $GITHUB_ENV
          else
            tar -czf ${{ steps.vars.outputs.asset_name }}.tar.gz -C staging .
            echo "archive_path=${{ steps.vars.outputs.asset_name }}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.archive_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
